apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert
  namespace: monitoring
spec:
  groups:
    - name: test
      rules:
        - alert: TestEmail
          expr: vector(1)
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Test email alert from Kubernetes"
            description: "This is a test alert to verify Alertmanager email configuration"
