name: Terraform

on:
  push:
    branches:
      - release/**
    paths:
      - "infrastructure/terraform/**"

  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage
          - prod

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ENVIRONMENT: ${{ github.event_name == 'workflow_dispatch'
    && github.event.inputs.environment
    || (github.ref_name == 'release/dev' && 'dev'
    || github.ref_name == 'release/stage' && 'stage'
    || 'prod') }}

permissions:
  contents: write

jobs:
  # Step 1: Terraform Apply
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: infrastructure/terraform
        run: terraform init -upgrade

      - name: Select Terraform Workspace
        working-directory: infrastructure/terraform
        run: |
          terraform workspace select $ENVIRONMENT || terraform workspace new $ENVIRONMENT

      - name: Terraform Apply
        working-directory: infrastructure/terraform
        env:
          TF_IN_AUTOMATION: true
        run: terraform apply -auto-approve -input=false -var="ENV_PREFIX=$ENVIRONMENT"
